name: Monthly Analytics Save

on:
  schedule:
    # Run on the last day of every month at 23:55 UTC
    - cron: '55 23 28-31 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  save-analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check if last day of month
      id: check-date
      run: |
        tomorrow=$(date -d "+1 day" +%d)
        if [ "$tomorrow" = "01" ]; then
          echo "is_last_day=true" >> $GITHUB_OUTPUT
        else
          echo "is_last_day=false" >> $GITHUB_OUTPUT
          echo "Not the last day of the month, skipping..."
        fi
        
    - name: Generate monthly analytics
      if: steps.check-date.outputs.is_last_day == 'true'
      run: |
        # Create the analytics directory if it doesn't exist
        mkdir -p assets/analytics
        
        # Get current month in YYYY-MM format
        CURRENT_MONTH=$(date +%Y-%m)
        
        # Create analytics file with placeholder data
        # In a real implementation, this would fetch actual Google Analytics data
        cat > assets/analytics/monthly-${CURRENT_MONTH}.json << EOF
        {
          "month": "${CURRENT_MONTH}",
          "views": $(shuf -i 500-2000 -n 1),
          "uniqueVisitors": [],
          "lastSaved": "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)",
          "domain": "kevin-ai.com",
          "generated": "automated",
          "analytics": {
            "topPages": [
              { "page": "/", "views": $(shuf -i 200-800 -n 1) },
              { "page": "/publications", "views": $(shuf -i 100-400 -n 1) },
              { "page": "/experience", "views": $(shuf -i 50-200 -n 1) },
              { "page": "/contact", "views": $(shuf -i 30-150 -n 1) }
            ],
            "note": "Replace with actual Google Analytics data"
          }
        }
        EOF
        
        echo "Generated analytics file for ${CURRENT_MONTH}"
        
    - name: Commit and push analytics data
      if: steps.check-date.outputs.is_last_day == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        CURRENT_MONTH=$(date +%Y-%m)
        
        git add assets/analytics/monthly-${CURRENT_MONTH}.json
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📊 Add monthly analytics data for ${CURRENT_MONTH}"
          git push
          echo "Analytics data committed and pushed"
        fi

    - name: Create summary
      if: steps.check-date.outputs.is_last_day == 'true'
      run: |
        CURRENT_MONTH=$(date +%Y-%m)
        echo "## Monthly Analytics Saved 📊" >> $GITHUB_STEP_SUMMARY
        echo "Successfully generated and committed analytics data for ${CURRENT_MONTH}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "- Review the generated data in \`assets/analytics/monthly-${CURRENT_MONTH}.json\`" >> $GITHUB_STEP_SUMMARY
        echo "- Update with actual Google Analytics data if needed" >> $GITHUB_STEP_SUMMARY
        echo "- The page view counter will automatically load this data" >> $GITHUB_STEP_SUMMARY 